name = "yongtong-store"
type = "javascript"
account_id = ""
workers_dev = false

[build]
command = "npm run build"
watch_paths = ["src/**/*.jsx", "src/**/*.css"]
cwd = "."

[env.production]
build = { command = "npm run build" }

[triggers]
crons = []

[[env.production.routes]]
pattern = "*"
zone_name = ""
